# Generated by Django 2.1.8 on 2019-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habbits',
            field=models.CharField(blank=True, choices=[('smoke', 'smoke'), ('drink', 'drink')], max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
