# Generated by Django 2.1.8 on 2019-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190603_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xray',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('did not check', 'did not check')], max_length=15),
        ),
    ]
