# Generated by Django 2.1.8 on 2019-06-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190603_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionField',
            new_name='QuestField',
        ),
    ]
