# Generated by Django 2.1.8 on 2019-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190603_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
