# Generated by Django 2.1.8 on 2019-06-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
