# Generated by Django 2.1.8 on 2019-06-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190604_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
