# Generated by Django 2.1.8 on 2019-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_answer_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
